### ISSUE TITLE
Crash when refreshing

### ISSUE THREAD

**Issue by InhouseMedia** [adamvanlente/ghit-app#5]
On my iPhone 5s the app crashes even refreshing the issue list.

**Comment by adamvanlente** [comment]
I am not able to replicate this problem (when refreshing the issue list), but did fix some incorrect behavior when refreshing the main repository list.

I've added some internal error reporting tools so that I can keep track of failed requests to the github api (which may or may not be the cause of the crashing).  

If you have any additional details that might help, please let me know.  Otherwise, I'll bump this issue once the new version is in the app store, and we'll see if that resolves it.

**Comment by InhouseMedia** [comment]
Thanks for the quick response.
The issue occurs when I add a new issue to my list and I refresh the list immediately after inserting.
I hope this helps.
p.s.
It's a great app. It fits my needs perfectly

**Comment by adamvanlente** [comment]
Thanks again for raising this issue.  The new version of ghit is live in the app store today, which should address this issue (I am unable to replicate the issue in this version).  

Apologies for the delay on this fix.  This version was in app-store-approval-purgatory for a few weeks while Apple and I argued over whether or not it looked correct on an iPad.  Just heard back this morning.
